version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
     # - ./db:/docker-entrypoint-initdb.d
    networks:
      - product

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: golang_backend
    restart: on-failure
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_SSLMODE: disable
      DB_TIMEZONE: Asia/Shanghai
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - product

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  product:
    driver: bridge